### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'rfft' with fsim and vsi

### ISSUE THREAD

**Issue by RashiqAzhan** [photosynthesis-team/piq#253]
**Describe the bug**
I have an `attribute` error that is preventing me from using the `fsim` and `vsi` functions. I tried using the example code in the docs but was not successful. Any help is appretiated.

Terminal Output:
```python
Traceback (most recent call last):
  File "...\.venv\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3044cfc208ce>", line 1, in <module>
    runfile('.../stackoverflow.py', wdir='...')
  File "...\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "...\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../stackoverflow.py", line 15, in <module>
    main()
  File "...\.venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File ".../stackoverflow.py", line 10, in main
    fsim_index: torch.Tensor = piq.fsim(x, y, data_range=1., reduction='none')
  File "...\.venv\lib\site-packages\piq\fsim.py", line 84, in fsim
    pc_x = _phase_congruency(
  File "...\.venv\lib\site-packages\piq\fsim.py", line 241, in _phase_congruency
    imagefft = torch.rfft(x, 2, onesided=False)
AttributeError: module 'torch' has no attribute 'rfft'
```

**To Reproduce**
Code used:
```python
from skimage import io
import torch
import piq

@torch.no_grad()
def main():
    x = torch.tensor(io.imread('scikit_image\cover\cover_1.tiff')).permute(2, 0, 1)[None, ...] / 255.
    y = torch.tensor(io.imread('scikit_image\stego\stego_1.tiff')).permute(2, 0, 1)[None, ...] / 255.

    fsim_index: torch.Tensor = piq.fsim(x, y, data_range=1., reduction='none')
    vsi_index: torch.Tensor = piq.vsi(x, y, data_range=1., reduction='none')

    print(fsim_index)
    print(vsi_index)

if __name__ == "__main__":
    main()
```

**Expected behavior**
I was hoping for the indexes to be printed in the console after execution but recevied the above error message instead.

**Comment by zakajd** [comment]
@RashiqAzhan please provide your PyTorch version and PIQ version.
Have you installed package from pip or directly from master branch?

@denproc  I think we fixed this issue in master branch but not yet pushed the release to pypi?

**Comment by RashiqAzhan** [comment]
PyTorch version: 1.8.1+cpu
PIQ version: 0.5.4
I have installed PIQ using pip.

**Comment by zakajd** [comment]
This bug was fixed in master branch, but we still didn't push the new update to `pip`.
Running this should help: `git clone git@github.com:photosynthesis-team/piq.git; cd piq; pip install .`

**Comment by RashiqAzhan** [comment]
I used the following command to get the package from PyPy. I am sorry for my inaccurate statement earlier. I used pipenv.
```
pipenv install -e git+https://github.com/photosynthesis-team/piq@master#egg=piq
```

Everything downloaded and installed properly it seems but the error still persists. Is there anything I'm doing wrong?

**Comment by zakajd** [comment]
That's strange, we have an explicit version check in master that should work for 1.8.1 and use proper function. 
Are you sure that everything is installed correctly?

https://github.com/photosynthesis-team/piq/blob/06ab98226b38482e3eea16db9c60fd1ef8d37cdf/piq/fsim.py#L243-L252

**Comment by RashiqAzhan** [comment]
I mean I uninstalled the existing PIQ and installed it using the above command. `piq.psnr` and various others are working and outputting results as expected. Is there anything I can do to check or provide more information?

Terminal Output:
```python
Installing -e git+https://github.com/photosynthesis-team/piq@master#egg=piq...
[  ==]to Pipfile's Installing piq... [packages]...
Installation Succeeded
Pipfile.lock (db4242) out of date, updating to (4076c0)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
 Locking...Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (4076c0)!
Installing dependencies from Pipfile.lock (4076c0)...
  ================================ 1/1 - 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

P.S. I have been looking for IW-PSNR, and IW-SSIM in the docs but was not able to find them. Can you point to me where they might be?

**Comment by zakajd** [comment]
Try following the error log and check if file in `..\.venv\lib\site-packages\piq\fsim.py` contains the lines I posted above. 

IW-SSIM and IW-PSNR are work in progress, partially copied implementation can be found in open PR: https://github.com/photosynthesis-team/piq/pull/201

**Comment by zakajd** [comment]
@RashiqAzhan did you fix the attribute error? What was the problem source?

**Comment by RashiqAzhan** [comment]
I'm sorry for the late reply. I solved by doing as you advised by installing from the master branch. I had to delete the virtual environment of the project to get it working. It was a pip issue I presume.
